ktor:
    application:
        modules:
            - io.spektacle.ApplicationKt.module
    deployment:
        port: 8080
storage:
    driverClassName: "org.postgresql.Driver"
    jdbcURL: "jdbc:postgresql://postgres:5432/hapkido"
    username: hapkido
    password: hapkido